// Generates src/components/icons.gen.ts from Phosphor Icons (MIT, phosphoricons.com).
// Only the icons and weights the panel uses are embedded, which keeps the bundle
// small. Run `npm run icons` after changing the list below.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const assets = join(root, 'node_modules/@phosphor-icons/core/assets')

// [export name, Phosphor icon, weight]
const ICONS = [
  ['LayoutDashboard', 'SquaresFour', 'regular'],
  ['Users', 'UsersThree', 'regular'],
  ['Network', 'Graph', 'regular'],
  ['Server', 'HardDrives', 'regular'],
  ['ShieldCheck', 'ShieldCheck', 'regular'],
  ['ScrollText', 'Scroll', 'regular'],
  ['Settings', 'GearSix', 'regular'],
  ['LogOut', 'SignOut', 'regular'],
  ['Moon', 'Moon', 'regular'],
  ['Sun', 'Sun', 'regular'],
  ['Languages', 'Translate', 'regular'],
  ['KeyRound', 'Key', 'regular'],
  ['Activity', 'Pulse', 'regular'],
  ['Zap', 'Lightning', 'regular'],
  ['Wifi', 'WifiHigh', 'regular'],
  ['Gauge', 'Gauge', 'regular'],
  ['Clock', 'Clock', 'regular'],
  ['Cpu', 'Cpu', 'regular'],
  ['HardDrive', 'Memory', 'regular'],
  ['QrCode', 'QrCode', 'regular'],
  ['CloudUpload', 'CloudArrowUp', 'regular'],
  ['Code2', 'Code', 'regular'],
  ['Download', 'DownloadSimple', 'regular'],
  ['Info', 'Info', 'regular'],
  ['Link2Off', 'LinkBreak', 'regular'],
  ['MessageCircle', 'ChatCircleDots', 'regular'],
  ['MessageSquareText', 'ChatText', 'regular'],
  ['Smartphone', 'DeviceMobile', 'regular'],
  ['Wand2', 'MagicWand', 'regular'],
  ['CheckCircle2', 'CheckCircle', 'regular'],
  ['RotateCcw', 'ArrowCounterClockwise', 'regular'],
  ['Pencil', 'PencilSimple', 'regular'],
  ['Trash2', 'Trash', 'regular'],
  ['ChartUp', 'ChartLineUp', 'regular'],
  ['Sparkle', 'Sparkle', 'regular'],
  ['Globe', 'GlobeHemisphereWest', 'regular'],
  ['UserCircle', 'UserCircle', 'regular'],
  ['Plus', 'Plus', 'bold'],
  ['X', 'X', 'bold'],
  ['Check', 'Check', 'bold'],
  ['Copy', 'Copy', 'bold'],
  ['ChevronLeft', 'CaretLeft', 'bold'],
  ['ChevronRight', 'CaretRight', 'bold'],
  ['Menu', 'List', 'bold'],
  ['Search', 'MagnifyingGlass', 'bold'],
  ['RefreshCw', 'ArrowsClockwise', 'bold'],
  ['ExternalLink', 'ArrowSquareOut', 'bold'],
  ['MoreHorizontal', 'DotsThreeOutline', 'bold'],
  ['Loader2', 'CircleNotch', 'bold'],
  ['PanelLeft', 'SidebarSimple', 'regular'],
  ['ChevronsUpDown', 'CaretUpDown', 'bold'],
  ['ArrowUpRight', 'ArrowUpRight', 'bold'],
  ['ArrowDownRight', 'ArrowDownRight', 'bold'],
  ['ArrowRight', 'ArrowRight', 'bold'],
  ['Export', 'Export', 'regular'],
  ['Calendar', 'CalendarBlank', 'regular'],
  ['Hourglass', 'HourglassMedium', 'regular'],
]

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

let out = '// Generated by scripts/gen-icons.mjs from Phosphor Icons (MIT License). Do not edit.\n'
out += 'export const ICON_PATHS: Record<string, string> = {\n'
for (const [name, icon, weight] of ICONS) {
  const file = join(assets, weight, `${kebab(icon)}${weight === 'regular' ? '' : '-' + weight}.svg`)
  const svg = readFileSync(file, 'utf8')
  const inner = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim()
  out += `  ${name}: ${JSON.stringify(inner)},\n`
}
out += '}\n'
writeFileSync(join(root, 'src/components/icons.gen.ts'), out)
console.log(`wrote ${ICONS.length} icons`)
