// Icon set for the panel: Phosphor Icons (phosphoricons.com, MIT), embedded
// locally so the UI never depends on a CDN. Navigation and feature icons use
// the two-tone "duotone" weight; small control glyphs use "bold". The SVG paths
// are generated by scripts/gen-icons.mjs (npm run icons).
import type { ComponentType } from 'react'
import { ICON_PATHS } from './icons.gen'

export type IconProps = { className?: string }
export type Icon = ComponentType<IconProps>

function make(name: string): Icon {
  const markup = { __html: ICON_PATHS[name] }
  const Svg = ({ className }: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" aria-hidden className={className} dangerouslySetInnerHTML={markup} />
  )
  Svg.displayName = name
  return Svg
}

export const LayoutDashboard = make('LayoutDashboard')
export const Users = make('Users')
export const Network = make('Network')
export const Server = make('Server')
export const ShieldCheck = make('ShieldCheck')
export const ScrollText = make('ScrollText')
export const Settings = make('Settings')
export const LogOut = make('LogOut')
export const Moon = make('Moon')
export const Sun = make('Sun')
export const Languages = make('Languages')
export const KeyRound = make('KeyRound')
export const Activity = make('Activity')
export const Zap = make('Zap')
export const Wifi = make('Wifi')
export const Gauge = make('Gauge')
export const Clock = make('Clock')
export const Cpu = make('Cpu')
export const HardDrive = make('HardDrive')
export const QrCode = make('QrCode')
export const CloudUpload = make('CloudUpload')
export const Code2 = make('Code2')
export const Download = make('Download')
export const Info = make('Info')
export const Link2Off = make('Link2Off')
export const MessageCircle = make('MessageCircle')
export const MessageSquareText = make('MessageSquareText')
export const Smartphone = make('Smartphone')
export const Wand2 = make('Wand2')
export const CheckCircle2 = make('CheckCircle2')
export const RotateCcw = make('RotateCcw')
export const Pencil = make('Pencil')
export const Trash2 = make('Trash2')
export const ChartUp = make('ChartUp')
export const Sparkle = make('Sparkle')
export const Globe = make('Globe')
export const UserCircle = make('UserCircle')

export const Plus = make('Plus')
export const X = make('X')
export const Check = make('Check')
export const Copy = make('Copy')
export const ChevronLeft = make('ChevronLeft')
export const ChevronRight = make('ChevronRight')
export const Menu = make('Menu')
export const Search = make('Search')
export const RefreshCw = make('RefreshCw')
export const ExternalLink = make('ExternalLink')
export const MoreHorizontal = make('MoreHorizontal')
export const Loader2 = make('Loader2')
