// Icon set for the panel: Lucide (lucide.dev, ISC), embedded locally so the UI
// never depends on a CDN. Stroke icons in the Lucide grammar (24 viewBox,
// round caps and joins, 1.75 stroke) take their colour from currentColor.
// The SVG paths are generated by scripts/gen-icons.mjs (npm run icons).
import type { ComponentType } from 'react'
import { ICON_PATHS } from './icons.gen'

export type IconProps = { className?: string }
export type Icon = ComponentType<IconProps>

function make(name: string): Icon {
  const markup = { __html: ICON_PATHS[name] }
  const Svg = ({ className }: IconProps) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.75}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
      className={className}
      dangerouslySetInnerHTML={markup}
    />
  )
  Svg.displayName = name
  return Svg
}

export const LayoutDashboard = make('LayoutDashboard')
export const Users = make('Users')
export const Network = make('Network')
export const Server = make('Server')
export const ShieldCheck = make('ShieldCheck')
export const ScrollText = make('ScrollText')
export const Settings = make('Settings')
export const LogOut = make('LogOut')
export const Moon = make('Moon')
export const Sun = make('Sun')
export const Monitor = make('Monitor')
export const Contrast = make('Contrast')
export const Bell = make('Bell')
export const Languages = make('Languages')
export const KeyRound = make('KeyRound')
export const Activity = make('Activity')
export const Zap = make('Zap')
export const Wifi = make('Wifi')
export const Gauge = make('Gauge')
export const Clock = make('Clock')
export const Cpu = make('Cpu')
export const HardDrive = make('HardDrive')
export const QrCode = make('QrCode')
export const CloudUpload = make('CloudUpload')
export const Code2 = make('Code2')
export const Download = make('Download')
export const Info = make('Info')
export const Link2Off = make('Link2Off')
export const MessageCircle = make('MessageCircle')
export const MessageSquareText = make('MessageSquareText')
export const Smartphone = make('Smartphone')
export const Wand2 = make('Wand2')
export const CheckCircle2 = make('CheckCircle2')
export const CircleAlert = make('CircleAlert')
export const Inbox = make('Inbox')
export const SearchX = make('SearchX')
export const RotateCcw = make('RotateCcw')
export const Pencil = make('Pencil')
export const Trash2 = make('Trash2')
export const ChartUp = make('ChartUp')
export const Sparkle = make('Sparkle')
export const Globe = make('Globe')
export const UserCircle = make('UserCircle')
export const UserPlus = make('UserPlus')
export const Calendar = make('Calendar')
export const Hourglass = make('Hourglass')
export const TrendingUp = make('TrendingUp')
export const TrendingDown = make('TrendingDown')
export const Rows = make('Rows')
export const Command = make('Command')
export const CornerDownLeft = make('CornerDownLeft')
export const Plus = make('Plus')
export const X = make('X')
export const Check = make('Check')
export const Copy = make('Copy')
export const ChevronLeft = make('ChevronLeft')
export const ChevronRight = make('ChevronRight')
export const ChevronDown = make('ChevronDown')
export const ChevronsUpDown = make('ChevronsUpDown')
export const Menu = make('Menu')
export const Search = make('Search')
export const RefreshCw = make('RefreshCw')
export const ExternalLink = make('ExternalLink')
export const MoreHorizontal = make('MoreHorizontal')
export const Loader2 = make('Loader2')
export const PanelLeft = make('PanelLeft')
export const ArrowUp = make('ArrowUp')
export const ArrowDown = make('ArrowDown')
export const ArrowUpDown = make('ArrowUpDown')
export const ArrowUpRight = make('ArrowUpRight')
export const ArrowDownRight = make('ArrowDownRight')
export const ArrowRight = make('ArrowRight')
export const Export = make('Export')
